### PR TITLE
Preserve user entries

### LINKED ISSUE #1: Preserve user entries
The `.goimportsignore` file supports comments. You could take advantage of this and preserve the user's explicit lines, putting your auto-generated entries in their own "section":

```
linux
foo/bar

# AUTO-GENERATED BY goimports-update-ignore
quux
a/b/c
# END-AUTO-GENERATED BY goimports-update-ignore
```

(with the user ones at top, for instance)

### PR DESCRIPTION
**Pull request by haya14busa**
Preserve lines which is not placed between auto generated markers.

	# Do not delete following entries.
	user/entries/1
	user/entries/2

	# Delete lines between markers when updating.
	# AUTO-GENERATED BY goimports-update-ignore
        genereated/by/goimports/1
        genereated/by/goimports/2
        ...
	# END-AUTO-GENERATED BY goimports-update-ignore

	# Do not delete following entries too.
	user/entries/3
	user/entries/4

Fixes #1

### CODE REVIEW

**Comment by pwaller** [comment]
Thanks for the PR.

I just tested this, but it unfortunately doesn't recognise existing auto-generated files as auto-generated, so it causes the length of my configuration to double when I run it. This is not obvious because it takes the existing file and puts it at the top, which currently says that it's auto-generated at the top, and then appends the new auto-generated file.

A simple fix would be to simply avoid changing the comment line which is inserted. What do you think?

One other quick idea: where the user lists a manual rule, do not list it in the automatic section. That way the user doesn't have to comment out multiple lines if they happen to have both a manual rule and an automatic one. I will merge this PR without this change though, it's only if you want to do it.

**Comment by haya14busa** [comment]
> A simple fix would be to simply avoid changing the comment line which is inserted. What do you think?

That's true. I fixed it.

> One other quick idea: where the user lists a manual rule, do not list it in the automatic section. That way the user doesn't have to comment out multiple lines if they happen to have both a manual rule and an automatic one.

We don't need to implement this idea, i guess. Because if users added manual section, goimports-update-ignore takes care them when updating (goimports takes care it internally), so there should no duplicated section.

**Comment by pwaller** [comment]
Thanks. I've tested and that seems to fix the problem.

> Because if users added manual section, goimports-update-ignore takes care them when updating (goimports takes care it internally), so there should no duplicated section.

I'm not sure we're understanding each other. My suggestion was to avoid duplicates appearing in the `.goimportsignore` file to avoid the confusion if a user wants to comment one out. To see this, move a line that appears in the auto-generated section outside into the manual section. Re-run goimports-update-ignore. It now appears twice, in both the manual section and outside. I think this can be confusing.

**Comment by haya14busa** [comment]
hmmm... that's true. I may misunderstood the goimports-update-ignore implementation somehow, i guess...

but, I think it's not so much important problem. if the directories is listed in generated section, it must be ignored regardless manual section contents. if go files are added to the directory, re-running goimports-update-ignore removes it from generated section and users can handle it for manual section.

I don't have strong motivation to implement the idea. I prefer creating another pull-request at least.
If you want to me to implement this, please let me know. Or could you please merging this pull-request?

**Comment by haya14busa** [comment]
Thank you! :bird: :+1:  :sparkles:

**Comment by pwaller** [comment]
I don't mind too much, I don't think it is a big problem. Thanks again :+1:.

**Pull request merged**
